# .travis.yml
language: go

# 指定 Go 版本
go:
  - 1.18.x
  - 1.23.x
  - tip  # 最新开发版本

# 操作系统
os:
  - linux
  - osx

# 设置 GOPATH 和构建目录
env:
  - GO111MODULE=on

# 安装依赖前的操作
before_install:
  - go mod download

# 安装项目依赖
install:
  - go get -t -v ./...

# 运行测试前的操作
before_script:
  - go vet ./...

# 运行测试
script:
  - go test -v -race ./...  # 启用竞态检测
  - go build -v ./...       # 确保项目可以构建

# 测试覆盖率
after_success:
  - bash <(curl -s https://codecov.io/bash)

# 设置通知
notifications:
  email:
    on_success: never
    on_failure: always

# 缓存依赖
cache:
  directories:
    - $GOPATH/pkg/mod
